<a href="https://colab.research.google.com/github/toyosigrace2-bit/---SWEP_200_ASSIGMENT02-/blob/main/SWEP_rpymb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**INTRODUCTION TO MACHINE LEARNING WITH PYTHON**

STRINGS
SET
DICTIINARY
LIST
INTEGER
TUPLE
FLOAT
BOOLEAN

In [ ]:
MIDE = 5
MIDE +5

10

In [ ]:
MIDE = {"name": "MIDE", "AGE": 14} #dictionary has two notations: keys; values
khan = [1, 2, 3, 4] #list
khan_1 = (1, 1, 2, 4, 5) #tuple
khan2 = 1; #integer
khan_3 = "captain" #string
khan_4 = 5.0 #float
khan_5 = True #boolean
khan_6 = {1, 2, 4, 6} #set
khan_7 = "c-a-p-t"

In [ ]:
#To check for the type of an object or variable,use type()
type(khan_4)

float

TYPE CASTING / CONVERSION

In [ ]:
type(str(khan2))

str

BASIC OPERATIONS

In [ ]:
#To check for the type of an object or variable, use type()
type(khan_5)

bool

In [ ]:
a = 5
b = 6
print(a+b) #addition
print(a-b) #subtraction
print(a/b) #division
print(a*b) #multiplication

11
-1
0.8333333333333334
30

Conditional statements & For loop

In [ ]:
"""
if type(khan2) ==int:
  print("MIDE IS A GOOD BOY")
else:
  print("MIDE IS A GIRL")
"""

#for loop allows iteration over sequence or list of values/ object
for i in khan:
  print(i**2)

1
4
9
16

*LIST COMPREHENSION: ONE OF THE METHODS THAT ENSURES OPTIMIZED MACHINE LEARNING TRAINING*

In [ ]:
#extract the even numbers from the khan list
even_number_list = []
odd_number_list = list() #list() initializes a list
for i in khan:
  if i % 2 ==0:
    even_number_list.append(i) #append is a method that adds an element or value to an existing/new list
  else:

    odd_number_list.append(i)




#LIST COMPREHENSION
even_number_list2 = [i for i in khan if i % 2 ==0]
odd_number_list2 = [i for i in khan if i % 2 !=0]

print(even_number_list2)
print(odd_number_list2)

[2, 4]
[1, 3]

BRIEF: *OBJECT ORIENTED PROGRAMMING*

In [ ]:
khan_7.split("-")

['c', 'a', 'p', 't']

In [ ]:
#defining the function
def AREA(1, )

In [ ]:
class Swep():
  def __init__(self, uni, level, dept, count = 47): #number of students = 47 :instantiate the attributes of the class into the memory
    self.uni = uni
    self.level = level
    self.dept = dept
    self.count = count

  def product_of_student_count_with_lenght_of_uni(self): #method, belongs to a class
    product = self.count * self.level
    return product

uni = "OAU"
level = 250
dept = "CHE"

#STEP1: INITIALIZE THE CLASS
swep = Swep(uni, level, dept)

#STEP2: PERFORM THE ACTION: to perform an operation under a class, use the dot notation; for example: initialized class.method
swep.product_of_student_count_with_lenght_of_uni()

11750

LOADING A DATASET WITH PYTHON USING PANDA

In [ ]:
import pandas as pd
"""

panda is a python library used for loading datasets,
and performing exploratory data analysis,
which includendata preprocessing, data.transformation;
data wrangling, etc.
"""

#load the dataset
df = pd.read_csv("/AI_SocialMedia_Student_Dataset.csv")
df

,Student_ID,Age,Gender,Education_Level,Daily_Social_Media_Hours,Daily_AI_Tool_Usage_Hours,Sleep_Hours,Physical_Activity_Hours,Mental_Health_Score,Physical_Health_Score
0,STU_00001,19,Male,College,5.32,1.21,7.30,1.41,74.06,98.90
1,STU_00002,16,Non-binary,High School,5.21,3.89,7.81,2.48,76.13,89.94
2,STU_00003,25,Male,University,3.61,2.65,6.34,0.06,65.01,76.75
3,STU_00004,23,Male,University,2.93,1.43,6.12,1.37,74.67,87.38
4,STU_00005,20,Non-binary,College,6.52,1.64,5.23,1.14,67.74,88.04
...,...,...,...,...,...,...,...,...,...,...
15995,STU_15996,16,Female,High School,3.89,4.67,5.15,1.41,76.64,81.90
15996,STU_15997,14,Male,High School,4.42,3.24,5.57,1.52,77.50,96.36
15997,STU_15998,15,Female,High School,0.00,2.89,5.56,1.81,77.56,99.58
15998,STU_15999,20,Female,College,0.30,5.09,5.61,1.25,80.69,82.03
15999,STU_16000,23,Male,University,3.18,1.70,6.81,0.18,72.85,82.53

.head(): by default, returns the first five rows,.tail returns the last five rows .info(): provides the summary of the dataset .describe(): provides the statistical summary of the datasheet

In [ ]:
df.head()

,Student_ID,Age,Gender,Education_Level,Daily_Social_Media_Hours,Daily_AI_Tool_Usage_Hours,Sleep_Hours,Physical_Activity_Hours,Mental_Health_Score,Physical_Health_Score
0,STU_00001,19,Male,College,5.32,1.21,7.30,1.41,74.06,98.90
1,STU_00002,16,Non-binary,High School,5.21,3.89,7.81,2.48,76.13,89.94
2,STU_00003,25,Male,University,3.61,2.65,6.34,0.06,65.01,76.75
3,STU_00004,23,Male,University,2.93,1.43,6.12,1.37,74.67,87.38
4,STU_00005,20,Non-binary,College,6.52,1.64,5.23,1.14,67.74,88.04

In [ ]:
df.tail()

,Student_ID,Age,Gender,Education_Level,Daily_Social_Media_Hours,Daily_AI_Tool_Usage_Hours,Sleep_Hours,Physical_Activity_Hours,Mental_Health_Score,Physical_Health_Score
15995,STU_15996,16,Female,High School,3.89,4.67,5.15,1.41,76.64,81.90
15996,STU_15997,14,Male,High School,4.42,3.24,5.57,1.52,77.50,96.36
15997,STU_15998,15,Female,High School,0.00,2.89,5.56,1.81,77.56,99.58
15998,STU_15999,20,Female,College,0.30,5.09,5.61,1.25,80.69,82.03
15999,STU_16000,23,Male,University,3.18,1.70,6.81,0.18,72.85,82.53

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16000 entries, 0 to 15999
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Student_ID                 16000 non-null  object
 1   Age                        16000 non-null  int64
 2   Gender                     16000 non-null  object
 3   Education_Level            16000 non-null  object
 4   Daily_Social_Media_Hours   16000 non-null  float64
 5   Daily_AI_Tool_Usage_Hours  16000 non-null  float64
 6   Sleep_Hours                16000 non-null  float64
 7   Physical_Activity_Hours    16000 non-null  float64
 8   Mental_Health_Score        16000 non-null  float64
 9   Physical_Health_Score      16000 non-null  float64
dtypes: float64(6), int64(1), object(3)
memory usage: 1.2+ MB

In [ ]:
df.describe()

,Age,Daily_Social_Media_Hours,Daily_AI_Tool_Usage_Hours,Sleep_Hours,Physical_Activity_Hours,Mental_Health_Score,Physical_Health_Score
count,16000.00000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000
mean,19.03875,4.541791,2.590624,6.545371,1.248359,72.493193,88.020465
std,3.76527,2.403044,1.679376,1.270515,1.038632,9.244818,9.691037
min,13.00000,0.000000,0.000000,2.000000,0.000000,32.560000,48.030000
25%,16.00000,2.840000,1.310000,5.680000,0.310000,66.760000,81.517500
50%,19.00000,4.500000,2.520000,6.540000,1.130000,73.750000,89.455000
75%,22.00000,6.180000,3.750000,7.410000,1.960000,79.550000,97.170000
max,25.00000,14.000000,9.500000,11.150000,5.000000,91.760000,99.980000

export dataframe to other file extensions, like csv, xlsx, etc.

In [ ]:
df.drop("Student_ID", axis=1, inplace=True) #setting axis to 1 means points to columns

NameError: name 'df' is not defined

In [ ]:
df

,Student_ID,Age,Gender,Education_Level,Daily_Social_Media_Hours,Daily_AI_Tool_Usage_Hours,Sleep_Hours,Physical_Activity_Hours,Mental_Health_Score,Physical_Health_Score
0,STU_00001,19,Male,College,5.32,1.21,7.30,1.41,74.06,98.90
1,STU_00002,16,Non-binary,High School,5.21,3.89,7.81,2.48,76.13,89.94
2,STU_00003,25,Male,University,3.61,2.65,6.34,0.06,65.01,76.75
3,STU_00004,23,Male,University,2.93,1.43,6.12,1.37,74.67,87.38
4,STU_00005,20,Non-binary,College,6.52,1.64,5.23,1.14,67.74,88.04
...,...,...,...,...,...,...,...,...,...,...
15995,STU_15996,16,Female,High School,3.89,4.67,5.15,1.41,76.64,81.90
15996,STU_15997,14,Male,High School,4.42,3.24,5.57,1.52,77.50,96.36
15997,STU_15998,15,Female,High School,0.00,2.89,5.56,1.81,77.56,99.58
15998,STU_15999,20,Female,College,0.30,5.09,5.61,1.25,80.69,82.03
15999,STU_16000,23,Male,University,3.18,1.70,6.81,0.18,72.85,82.53

In [ ]:
df.to_csv("swep.csv", index = False)